### ISSUE TITLE
Issue with running Paramtovary.txt file for V0 but not PB2A

### ISSUE THREAD

**Issue by giovannivizcarra** [chill90/BoloCalc#1]
1. ![image](https://user-images.githubusercontent.com/62725355/77700710-faec5000-6f71-11ea-8619-7e4fabb80f5b.png)
2. ![image](https://user-images.githubusercontent.com/62725355/77700703-f6c03280-6f71-11ea-9bcb-c8f13d006852.png)

I attempted to run the paramtovary.txt file to as shown in image 2 above for both experiment PB2A and the example experiment V0 and got the error shown in image 1. There are two red boxes in image 1 to show that I ran the experiment fine with PB2A but was unable to run for V0.

**Comment by chill90** [comment]
Great find. It turns out that the program didn't know how to vary a parameter when the initial value was set to "NA." I've added a conditional statement to parameter.py to handle this situation

This will be fixed in v0.b10.7

**Comment by giovannivizcarra** [comment]
Yup that did it!
