### ISSUE TITLE
NaN Txt Files

### ISSUE THREAD

**Issue by giovannivizcarra** [chill90/BoloCalc#2]
1. ![image](https://user-images.githubusercontent.com/62725355/77701195-f5dbd080-6f72-11ea-97f8-a9e933a5302a.png)
2. ![image](https://user-images.githubusercontent.com/62725355/77701175-ec526880-6f72-11ea-8dca-d8374d7b46d7.png)
3. ![Screen Shot 2020-03-26 at 3 11 02 PM](https://user-images.githubusercontent.com/62725355/77701687-21ab8600-6f74-11ea-8da1-d39ebb867534.png)

I attempted to run the paramstovary.txt file as shown in image 1 and got a new type of error as shown in image 2. I still got a Cam_1 and Cam_2 txt file created in the ParamVary folder but I got a bunch of NaN and 0.00 values as shown in image 3.

**Comment by chill90** [comment]
This one was tricky.

You were varying the frequency of a band that was originally 150 GHz all the way down to 90 - 100 GHz. This highlighted that when changing the band by a significant amount, the the frequencies to be integrated over must adjust. This is fixed in v0.b10.8

**Comment by giovannivizcarra** [comment]
1.![Screen Shot 2020-03-31 at 8 32 24 AM](https://user-images.githubusercontent.com/62725355/78044981-37c99580-732a-11ea-9481-dd113cb20738.png)

2.![Screen Shot 2020-03-31 at 8 39 53 AM](https://user-images.githubusercontent.com/62725355/78045879-4e242100-732b-11ea-832e-7752679e94e6.png)


Looks great! It works great now. I am not sure if this is a real issue but found I still get a similar NaN issue when the band center is 1GHz or 2GHz as seen in image 1. Nonetheless, those are the only values I get NaN for. I tried ranging the band center up to 400GHz in another run and everything worked as needed. The only reason I point this out is because the user manual says that the allowed values range from (0, +∞).  Other than that this can be closed

**Comment by chill90** [comment]
So technically, the band center can be between (2 * fres, \infty), but this is a small enough detail that I am going to leave it alone. If you were using bolocalc to simulate an instrument with a 1 GHz or 2 GHz band center, you certainly wouldn't use a frequency resolution of 1 GHz to do it.
