### ISSUE TITLE
No txt File

### ISSUE THREAD

**Issue by giovannivizcarra** [chill90/BoloCalc#3]
1. ![No_Txt_File_Created_Both PB2A_and_V0](https://user-images.githubusercontent.com/62725355/77707045-40fce000-6f81-11ea-903c-3b399cc6fea3.png)
2.  ![Return_value_for_No_txt_file](https://user-images.githubusercontent.com/62725355/77707092-5bcf5480-6f81-11ea-8fac-bd047fc2458b.png)

I attempted to run image 1 for both experiments PB2A and example V0. I did not get any error message as seen in image 2 but there was no ParamVary folder created for either the PB2A or V0. I even ran it twice for V0 as seen by the red box in image 2 and I did not get a txt file.

**Comment by chill90** [comment]
Good catch. 

This was a bug in vary.py with case comparison for some optical elements and some parameters. I fixed that error in v0.b10.9

**Comment by giovannivizcarra** [comment]
1. ![Screen Shot 2020-03-31 at 8 55 11 AM](https://user-images.githubusercontent.com/62725355/78047561-5aa97900-732d-11ea-8add-d5c6d485d0fa.png)

Thanks! So I ran the same parameters as in the original comment and it appears to work but there was still no txt file created for cam_2 in the paramvary folder as seen in image 1. I know I am specifically changing the params to ch 1 and not 2 but for every simulation I have run I usually get a txt file for both Cam_1 and Cam_2 even if I do not make any changes to a specific Ch. Again I am not sure if this is a real issue anymore since I did get a txt file.

**Comment by chill90** [comment]
Yeah, so BoloCalc only generates text files when needed. If nothing in Cam_2 changes, then no text file is generated; that's the case you're seeing here. Now, if you ran some other parameter in Cam_2 at this point, you would see in your paramVary/ directory both Cam_1 and Cam_2. However, Cam_1 wouldn't have been updated by the Cam_2 simulation, even though the file is still there.

Basically, BoloCalc only writes what it needs to (overwriting if necessary) but doesn't delete files outright, if that makes sense. This is to increase program speed, as file writing carries significant overhead.

**Comment by giovannivizcarra** [comment]
Gotcha thank you!
