### ISSUE TITLE
Issue with Folder Names 

### ISSUE THREAD

**Issue by giovannivizcarra** [chill90/BoloCalc#4]
1. ![Screen Shot 2020-03-30 at 8 38 24 PM](https://user-images.githubusercontent.com/62725355/77986423-e4285f00-72cb-11ea-8868-24b1286c98f9.png)

I dont think the program allows you to design your own telescope or camera names. I think the program specifically looks for a telescope or camera folder named "Tel" and "Cam." Image 1 shows that I tried to run the Simons Observatory experiment. The first keyerror marked by a red box shows that the program was looking for a Folder labeld "TEL." 

To test my idea I specifically made a copy of the SAT folder and renamed it "Tel." However, when I ran the simulation I then got another error seen in the blue box specifically looking for a "Cam" folder. Which makes me think that I cannot create a Telescope or Camera name which may be an issue if there are multiple cameras.

**Comment by chill90** [comment]
This is working fine for me. Perhaps you forgot to change the telescope name in paramsToVary.txt after changing the filename?

**Comment by giovannivizcarra** [comment]
Shoot! I am sorry for any confusion this may have caused. Totally my mistake
