### ISSUE TITLE
Index mapping error in calculating total CMB and RJ map depth

### ISSUE THREAD

**Issue by ktcrowley** [chill90/BoloCalc#6]
In sensitivity.txt file in the "Tel" directory under an Experiment, appears that the total CMB-unit map depth is incorrectly calculated as the inverse-variance coadd of the channel correlation factor; also, the total RJ-unit map depth calculation uses the CMB-unit values. Looks like column indices are off by 1. This also appears in the more detailed sensitivity.txt in the "Cam" directory; i.e. the total CMB map depth can most clearly be seen in that file as NOT being the inverse-variance coadd of the individual channel CMB map depths.

**Comment by chill90** [comment]
Fixed in v0.b10.10, along with two other bugs related to the minimum allowed values for input probability distributions. Thanks for pointing this out, Kevin!

**Comment by chill90** [comment]
Oh, if you could pull and make sure the error is fixed, then either you or I can close the ticket. No rush, of course. Just let me know.
